autoSaveInterval: 20

regions:
  GOLD_BLOCK:
    x: 50
    z: 50
    y: 20

limit: 3

messages:
  on_enter: "&aВы вошли в регион игрока %arg%"
  on_leave: "&eВы покинули регион игрока %arg%"
  on_first_enter: "&aВы вошли в регион игрока %arg%"
  on_limit: "&cПревышен лимит регионов %arg%"
  on_create: "&aРегион создан"
  on_delete: "&eРегион удалён"
  region_crosses: "&cНельзя ставить регион: он пересекается с регионом игрока %arg%"
  not_owner: "&cВы не являетесь владельцем!"
  should_hold_golden_block: "&cВы должны держать золотой блок!"
  block_is_region: "&aБлок помечен!"
  meta_not_has_been: "&cНе удалось создать мета-данные для блока."
  block_not_for_region: "Этот блок не подходит для создания региона."
  unsupported_block: "Блок %arg% не поддерживается для регионов."
  region_block: "&aРегион-блок"

